### ISSUE TITLE
config/Coldbox.cfc - non-existing exception handler is confusing

### ISSUE THREAD

**Issue by TheRealAgentK** [coldbox-templates/rest-hmvc#16]
config/Coldbox.cfc has `exceptionHandler` set to `v1:Echo.onError`.

`Echo.onError` doesn't exist in the template application. 

It seems that when in this case a runtime error in  `Echo.index` occurs (say, a Division by Zero), `RestHandler.onError` gets called twice in development mode somehow. The first execution has the actual runtime error in `arguments.exception` when being dumped. The second execution is an empty struct.

This execution then fails in line 176, (`throw( object=arguments.exception )`) with a Lucee serialisation error.

If  `exceptionHandler` set to `v1:Echo.onError` is *not* set to a missing handler, but left blank, `RestHandler.onError` works correctly. The same is true when `exceptionHandler` actually points to a handler that exists.

There might be a separate issue in the `RestHandler` with the way `onError` throws the exception (again) in development mode to get to the error template. Or maybe there's some mechanism needed to prevent it from running into a lower-level CFML error.

But from this template's point of view, I think that by default, `exceptionHandler` should either be left empty or be set to a sample function that actually exists (in Echo) to make it easier for people using this template as their starting point.

**Comment by TheRealAgentK** [comment]
Result of dumping arguments.exception in `RestHandler.onError`:

First: actual exception
Second: empty struct
Third: Serialization error because of empty struct being thrown as `object` in line 176.

![localhost_8080_api_v1_echo_index](https://user-images.githubusercontent.com/322372/187094412-68a5d65c-20bc-48c9-96e1-a8c910f58149.png)

**Comment by lmajano** [comment]
I think that's a good point @TheRealAgentK .  Basically the `echo.onError` doesn't exist because it's inherited by the RestHandler.  However, I am not sure where the double executions would come up, that's baffling.  Since the convention for localized event handling is `onError()` locally. I am guessing it traps that.

```
} catch ( any e ) {
			// onError convention
			if ( oHandler._actionExists( "onError" ) ) {
				results.data = oHandler.onError(
					event          = oRequestContext,
					rc             = args.rc,
					prc            = args.prc,
					faultAction    = results.ehBean.getmethod(),
					exception      = e,
					eventArguments = arguments.eventArguments
				);
			} else {
				// Bubble up the error
				rethrow;
			}
		}
```
That's from the controller. So I am guessing maybe there's a recursion somewhere dealing with the RestHandler specifically.  I will have to investigate it.

However, removing the global exception handler might alleviate the issue, but then any exception now that is NOT under the rest handler will fail.  Could it be that we have an explicit try/catch in the around handler which calls the `onAnyOtherException` and then we rethrow?

```
} catch ( Any e ) {
			arguments.exception = e;
			this.onAnyOtherException( argumentCollection = arguments );
			// If in development, let's show the error template
			if ( getSetting( "environment" ) eq "development" ) {
				rethrow;
			}
		}
```

**Comment by lmajano** [comment]
This is fixed in `be` of ColdBox. It was a recursion issue.
